#!/bin/bash
# This script creates entries for all the sorts in the sorts directory.
SORTS="include/sorts.h"

headers="#include<vector>"$'\n'
vector="std::vector<SortContainer> sorts = {"$'\n'
for f in sorts/*.h; do
    fname=$(basename "$f")
    sortname="${fname%.*}"
    headers+="#include \"$fname\""$'\n'
    vector+="    {\"$sortname\", $sortname},"$'\n'
done
vector+="};"$'\n'

echo "// This file is auto-generated by sortGen.sh. Do not edit directly."$'\n' > $SORTS
echo "#pragma once"$'\n' >> $SORTS
echo "$headers" >> $SORTS
echo "$vector" >> $SORTS